// Regenerates worker/src/prices.ts from LiteLLM's public price list (the source ccusage and tokscale use).
// Run: node scripts/update-prices.mjs
import { writeFileSync } from 'node:fs'

const SOURCE = 'https://raw.githubusercontent.com/BerriAI/litellm/main/model_prices_and_context_window.json'
const all = await (await fetch(SOURCE)).json()
const perM = (v) => Math.round((v ?? 0) * 1e6 * 1e4) / 1e4
// First-party provider prices, keyed by model name without a provider prefix ("moonshot/kimi-k2" -> "kimi-k2").
// Claude models from Anthropic; other tools' models from their own providers.
const PROVIDERS = ['anthropic', 'openai', 'moonshot', 'deepseek', 'gemini', 'xai', 'mistral', 'zai', 'minimax', 'dashscope']
const byName = new Map()
for (const [k, v] of Object.entries(all)) {
  if (!PROVIDERS.includes(v.litellm_provider) || !v.input_cost_per_token || (v.mode && v.mode !== 'chat' && v.mode !== 'responses')) continue
  const name = k.split('/').pop()
  const rank = PROVIDERS.indexOf(v.litellm_provider)
  if (!byName.has(name) || rank < byName.get(name).rank) byName.set(name, { v, rank })
}
const rows = [...byName.entries()]
  .sort(([a], [b]) => a.localeCompare(b))
  .map(([k, { v }]) => `  '${k}': [${perM(v.input_cost_per_token)}, ${perM(v.output_cost_per_token)}, ${perM(v.cache_creation_input_token_cost)}, ${perM(v.cache_read_input_token_cost)}, ${perM(v.cache_creation_input_token_cost_above_1hr ?? v.cache_creation_input_token_cost)}],`)
writeFileSync(new URL('../worker/src/prices.ts', import.meta.url), `// Generated by scripts/update-prices.mjs from LiteLLM (${new Date().toISOString().slice(0, 10)}). Do not edit by hand.
// USD per million tokens: [input, output, cache write (5 min), cache read, cache write (1 hour)]. An API-equivalent estimate, not a bill.
export const PRICES: Record<string, [number, number, number, number, number]> = {
${rows.join('\n')}
}
`)
console.log(`${rows.length} models written`)
